DROP TABLE IF EXISTS TB_HEROES;

CREATE TABLE TB_HEROES (
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NAME TEXT NOT NULL,
  POWER TEXT NOT NULL
)

INSERT INTO TB_HEROES (NAME, POWER)
VALUES
  ('Batman', 'Intelligence'),
  ('Flash', 'Speed'),
  ('Aquaman', 'Telepathy')


SELECT * FROM TB_HEROES;
SELECT * FROM TB_HEROES WHERE NAME = 'Batman';

UPDATE TB_HEROES
SET POWER = 'Intelligence, Money'
WHERE ID = 1;

INSERT INTO TB_HEROES (NAME, POWER) VALUES ('Goku', 'Genki Dama');
DELETE FROM TB_HEROES WHERE ID = 4;
